language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-training' ]; then cd .. && eval "mv $currentfolder generator-training" && cd generator-training; fi

